# Generated by Django 5.2.16 on 2026-07-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('export', 'Export'), ('delete', 'Delete')], max_length=20)),
                ('username', models.CharField(max_length=150)),
                ('user_email', models.CharField(blank=True, default='', max_length=254)),
                ('performed_by', models.CharField(max_length=150)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
