# Generated by Django 5.2.16 on 2026-07-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_unique_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
