"""
Django settings for eve project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
DJANGO_ENV_NAME = config("DJANGO_ENV", default="prod")
DEPLOYMENT_ENVIRONMENT = config(
    "DEPLOYMENT_ENVIRONMENT",
    default=config("RAILWAY_ENVIRONMENT_NAME", default=""),
)
RELEASE_SHA = config(
    "RELEASE_SHA",
    default=config("RAILWAY_GIT_COMMIT_SHA", default=""),
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", default="dev-unsafe-secret")
SECRET_KEY_FALLBACKS = config("DJANGO_SECRET_KEY_FALLBACKS", default="", cast=Csv())

# Safe default; overridden by dev.py / prod.py
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party
    "rest_framework",
    "drf_spectacular",
    "drf_spectacular_sidecar",  # serves Swagger UI assets locally (CSP)
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",

    # Our apps
    "core",
    "accounts",
    "ecommerce",
    "payments",
    "api",
]

MIDDLEWARE = [
    'core.middleware.TrustedProxyMiddleware',
    'core.middleware.RequestIDMiddleware',
    'core.middleware.RequestMetricsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'core.middleware.AdminIPAllowlistMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Admin is served from a configurable, non-default path in production
ADMIN_URL = config("DJANGO_ADMIN_URL", default="admin/")

# When True the admin login additionally requires a one-time password
# (django-otp TOTP). Enabled by default in production settings.
ADMIN_REQUIRE_MFA = config("DJANGO_ADMIN_REQUIRE_MFA", default=False, cast=bool)

# Comma-separated IPs allowed to reach the admin. Empty disables the check
# (use when the admin is protected by VPN/SSO at the proxy instead).
ADMIN_ALLOWED_IPS = config("DJANGO_ADMIN_ALLOWED_IPS", default="", cast=Csv())

# --- Explicit cookie policy (secure flags are set in prod.py) ---
SESSION_COOKIE_HTTPONLY = True          # JS must never read the session
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 14 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
CSRF_COOKIE_HTTPONLY = True             # forms use {% csrf_token %}, no JS access needed
CSRF_COOKIE_SAMESITE = "Lax"
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True

ROOT_URLCONF = 'eve.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eve.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
SALEOR_GRAPHQL_URL = config("SALEOR_GRAPHQL_URL", default="")
SALEOR_CHANNEL = config("SALEOR_CHANNEL", default="default-channel")
SALEOR_API_TOKEN = config("SALEOR_API_TOKEN", default="")

# Saleor signs webhook bodies as detached RS256 JWS. When unset, the JWKS URL
# is derived from SALEOR_GRAPHQL_URL's origin.
SALEOR_JWKS_URL = config("SALEOR_JWKS_URL", default="")
SALEOR_JWKS_CACHE_SECONDS = config("SALEOR_JWKS_CACHE_SECONDS", default=3600, cast=int)

# Checkout stays disabled until the Saleor integration tests pass against a
# real instance (see payments/tests.py::SaleorIntegrationTests). Flip only
# after that, and only with a reachable Saleor JWKS endpoint.
CHECKOUT_ENABLED = config("CHECKOUT_ENABLED", default=False, cast=bool)

# How long Mongo-cached Saleor products stay fresh before re-fetching
PRODUCT_CACHE_TTL_SECONDS = config("PRODUCT_CACHE_TTL_SECONDS", default=3600, cast=int)
CHECKOUT_RECOVERY_GRACE_SECONDS = config(
    "CHECKOUT_RECOVERY_GRACE_SECONDS", default=300, cast=int
)

# --- Data retention (enforced by manage.py purge_expired_data, run daily)
CONTACT_MESSAGE_RETENTION_DAYS = config("CONTACT_MESSAGE_RETENTION_DAYS", default=365, cast=int)
ABANDONED_CART_RETENTION_DAYS = config("ABANDONED_CART_RETENTION_DAYS", default=365, cast=int)
WEBHOOK_EVENT_RETENTION_DAYS = config("WEBHOOK_EVENT_RETENTION_DAYS", default=90, cast=int)

# Backup evidence is supplied by provider automation, never by application
# code. `audit_data_protection` fails when evidence is absent or stale.
POSTGRES_BACKUP_LAST_SUCCESS_AT = config("POSTGRES_BACKUP_LAST_SUCCESS_AT", default="")
MONGODB_BACKUP_LAST_SUCCESS_AT = config("MONGODB_BACKUP_LAST_SUCCESS_AT", default="")
RESTORE_TEST_LAST_SUCCESS_AT = config("RESTORE_TEST_LAST_SUCCESS_AT", default="")
BACKUP_MAX_AGE_HOURS = config("BACKUP_MAX_AGE_HOURS", default=36, cast=int)
RESTORE_TEST_MAX_AGE_DAYS = config("RESTORE_TEST_MAX_AGE_DAYS", default=100, cast=int)
BACKUP_ENCRYPTION_CONFIRMED = config("BACKUP_ENCRYPTION_CONFIRMED", default=False, cast=bool)
BACKUP_OFFSITE_CONFIRMED = config("BACKUP_OFFSITE_CONFIRMED", default=False, cast=bool)

# --- Cache / sessions: Redis when REDIS_URL is set, else per-process memory.
# Production requires REDIS_URL (prod.py) so rate limits, lockouts, and
# sessions are shared across workers.
REDIS_URL = config("REDIS_URL", default="")

# Celery uses a distinct broker URL so production can isolate queues from the
# cache/session/rate-limit Redis instance. Development may deliberately reuse
# REDIS_URL; production deployment should set CELERY_BROKER_URL explicitly.
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default=REDIS_URL)
CELERY_RESULT_BACKEND = None
CELERY_TASK_IGNORE_RESULT = True
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_TRANSPORT_OPTIONS = {"visibility_timeout": 300}
CELERY_BROKER_POOL_LIMIT = 10
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SOFT_TIME_LIMIT = 50
CELERY_TASK_TIME_LIMIT = 60
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_CANCEL_LONG_RUNNING_TASKS_ON_CONNECTION_LOSS = True
CELERY_TASK_ROUTES = {
    "accounts.tasks.*": {"queue": "email"},
    "payments.tasks.process_webhook_event": {"queue": "webhooks"},
    "payments.tasks.recover_pending_webhooks": {"queue": "webhooks"},
    "payments.tasks.reconcile_orders": {"queue": "orders"},
    "core.tasks.purge_expired_data": {"queue": "maintenance"},
    "core.tasks.sample_resources": {"queue": "maintenance"},
    "ecommerce.tasks.refresh_catalogue": {"queue": "catalogue"},
}
CELERY_BEAT_SCHEDULE = {
    "recover-pending-webhooks": {
        "task": "payments.tasks.recover_pending_webhooks",
        "schedule": 60.0,
    },
    "reconcile-saleor-orders": {
        "task": "payments.tasks.reconcile_orders",
        "schedule": 60.0 * 60.0,
    },
    "purge-expired-data": {
        "task": "core.tasks.purge_expired_data",
        "schedule": 60.0 * 60.0 * 24.0,
    },
    "sample-resources": {
        "task": "core.tasks.sample_resources",
        "schedule": 60.0,
    },
    "refresh-catalogue": {
        "task": "ecommerce.tasks.refresh_catalogue",
        "schedule": 300.0,
    },
}

if REDIS_URL:
    from core.cache import SafeJSONSerializer

    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                # JSON instead of pickle: a compromised Redis must not be
                # able to execute code in the app (threat model R2)
                "serializer": SafeJSONSerializer(),
                # Passed through to redis.ConnectionPool
                "max_connections": config("REDIS_MAX_CONNECTIONS", default=50, cast=int),
                "socket_connect_timeout": 2,
                "socket_timeout": 2,
                "retry_on_timeout": True,
            },
            "TIMEOUT": 300,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

# cached_db: reads served from Redis, writes mirrored to PostgreSQL, so a
# Redis flush/eviction/failover never logs users out. PostgreSQL stays the
# authoritative store for sessions, orders, and payments.
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

# --- Email (password reset, email verification). Console backend by default;
# production configures SMTP in prod.py.
EMAIL_BACKEND = config(
    "EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@localhost")
PUBLIC_BASE_URL = config("PUBLIC_BASE_URL", default="http://localhost:8000")

# DB_ENGINE=sqlite gives a zero-dependency evaluation path: `runserver`
# works on a fresh clone with no PostgreSQL installed. prod.py refuses it,
# so it can never reach a deployed environment.
DB_ENGINE = config("DB_ENGINE", default="postgresql")

if DB_ENGINE == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME", default="eve_db"),
        "USER": config("DB_USER", default="eve_user"),
        "PASSWORD": config("DB_PASSWORD", default="password"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
        # Persistent connections with health checks; put PgBouncer in front
        # when worker count × CONN_MAX_AGE pressure approaches max_connections
        "CONN_MAX_AGE": config("DB_CONN_MAX_AGE", default=60, cast=int),
        "CONN_HEALTH_CHECKS": True,
    }
    }
MONGODB = {
    "HOST": config("MONGODB_URI", default="mongodb://localhost:27017"),
    "DB_NAME": config("MONGODB_DB_NAME", default="EVEDB"),
    "MAX_POOL_SIZE": config("MONGODB_MAX_POOL_SIZE", default=50, cast=int),
    # Lower this locally so a machine without MongoDB fails fast
    "SERVER_SELECTION_TIMEOUT_MS": config(
        "MONGODB_SERVER_SELECTION_TIMEOUT_MS", default=5000, cast=int
    ),
}

# Reverse proxies whose X-Forwarded-For may be trusted for the client IP
# (rate limiting, admin allowlist). Empty = direct connections only.
TRUSTED_PROXIES = config("DJANGO_TRUSTED_PROXIES", default="", cast=Csv())

# Multiplies every per-IP rate limit. Exists so staging load tests aren't
# measuring 429s (loadtest/README.md). MUST stay 1 in production — a deploy
# check (eve.W002) fails the release otherwise.
RATE_LIMIT_SCALE = config("RATE_LIMIT_SCALE", default=1, cast=int)

# API tokens are hashed at rest and expire (threat model R11)
API_TOKEN_TTL_DAYS = config("API_TOKEN_TTL_DAYS", default=30, cast=int)

# Server-Timing exposes per-request app/db/mongo timings to the client.
# Useful for debugging and for the load test's breakdown; disabled in
# production because it removes network noise from timing analysis
# (threat model R13). Staging re-enables it explicitly.
SERVER_TIMING_ENABLED = config("SERVER_TIMING_ENABLED", default=True, cast=bool)

# --- Request size limits: bots and abuse, not legitimate form traffic
DATA_UPLOAD_MAX_MEMORY_SIZE = 1 * 1024 * 1024   # 1 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 1 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 200

REST_FRAMEWORK = {
    # Explicit: session auth only (no basic auth), authenticated by default,
    # JSON only — the browsable API is re-enabled in dev.py
    # Session auth for the browser (CSRF-protected), token auth for mobile
    # and server-to-server clients. Basic auth is deliberately absent.
    # Token first: it supplies the WWW-Authenticate header, so a bad or
    # missing credential yields 401 (not DRF's session-auth default of 403).
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "api.authentication.HashedTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "EXCEPTION_HANDLER": "api.errors.exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    # Fail-open variants: a cache outage must not 500 the whole API
    "DEFAULT_THROTTLE_CLASSES": [
        "api.throttling.AnonRateThrottle",
        "api.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/min",
        "user": "120/min",
        # Order placement is far more expensive (and risky) than a read
        "checkout": "10/min",
        # Credential endpoint: brute-force surface
        "token": "10/min",
    },
}

# LOG_FORMAT=json emits one JSON object per line with correlation IDs
# (prod default); "console" keeps human-readable output (dev default).
LOG_FORMAT = config("LOG_FORMAT", default="console")
LOG_LEVEL = config("LOG_LEVEL", default="INFO")

SPECTACULAR_SETTINGS = {
    "TITLE": "Eve API",
    "DESCRIPTION": (
        "REST API for the Eve VR-experience store: catalogue, cart, "
        "idempotent checkout, and order history.\n\n"
        "Authenticate with a session cookie (browser) or "
        "`Authorization: Token <key>` (mobile / server-to-server). Errors "
        "always use the envelope `{\"error\": {code, message, details, "
        "request_id}}`; branch on `code` and quote `request_id` in reports."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,  # don't document the schema endpoint itself
    "PREPROCESSING_HOOKS": ["api.schema_hooks.only_v1_endpoints"],
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/v1",
    "TAGS": [
        {"name": "products", "description": "Public catalogue."},
        {"name": "cart", "description": "The signed-in user's cart."},
        {"name": "checkout", "description": "Idempotent order placement."},
        {"name": "orders", "description": "Order history (own orders only)."},
        {"name": "account", "description": "Profile and token exchange."},
    ],
    # Assets from the sidecar package, not a CDN — the CSP forbids
    # third-party script/style origins.
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {"()": "core.logging.RequestIdFilter"},
        "redact": {"()": "core.logging.SensitiveDataFilter"},
    },
    "formatters": {
        # Both formatters scrub exception blocks, which bypass log filters
        "verbose": {"()": "core.logging.ConsoleFormatter"},
        "json": {"()": "core.logging.JsonFormatter"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json" if LOG_FORMAT == "json" else "verbose",
            "filters": ["request_id", "redact"],
        },
    },
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
    "loggers": {
        # 4xx/5xx responses and unhandled exceptions
        "django.request": {"level": "WARNING"},
        # CSRF failures, DisallowedHost, suspicious operations
        "django.security": {"level": "WARNING"},
        # One structured event per request (latency, status, db time)
        "eve.requests": {"level": "INFO"},
    },
}

# --- Exception monitoring (Sentry): active only when SENTRY_DSN is set.
# send_default_pii stays False and the scrubber strips cookies and auth
# headers — no credentials, health data, or payment data may reach Sentry.
SENTRY_DSN = config("SENTRY_DSN", default="")
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    def _scrub_sentry_event(event, hint):
        request = event.get("request") or {}
        request.pop("cookies", None)
        headers = request.get("headers") or {}
        for header in ("Authorization", "Cookie", "X-Api-Key", "Saleor-Signature"):
            headers.pop(header, None)
        return event

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        environment=config("DJANGO_ENV", default="prod"),
        send_default_pii=False,
        traces_sample_rate=config("SENTRY_TRACES_SAMPLE_RATE", default=0.0, cast=float),
        before_send=_scrub_sentry_event,
    )

# --- Password hashing
# Argon2id is the OWASP-preferred hasher and, on the small shared vCPUs this
# runs on, materially cheaper than Django's 1.2M-iteration PBKDF2 (measured:
# a login cost ~3.2s of CPU on staging). The PBKDF2 hashers stay listed so
# existing passwords still verify; Django transparently upgrades each hash
# on the owner's next successful login.
# Note: Argon2 is memory-hard (~100 MiB per concurrent hash by default);
# budget RAM as workers x threads x memory_cost.
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
