"""
Django settings for eve project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", default="dev-unsafe-secret")

# Safe default; overridden by dev.py / prod.py
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party
    "rest_framework",
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",

    # Our apps
    "core",
    "accounts",
    "ecommerce",
    "payments",
]

MIDDLEWARE = [
    'core.middleware.TrustedProxyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'core.middleware.AdminIPAllowlistMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Admin is served from a configurable, non-default path in production
ADMIN_URL = config("DJANGO_ADMIN_URL", default="admin/")

# When True the admin login additionally requires a one-time password
# (django-otp TOTP). Enabled by default in production settings.
ADMIN_REQUIRE_MFA = config("DJANGO_ADMIN_REQUIRE_MFA", default=False, cast=bool)

# Comma-separated IPs allowed to reach the admin. Empty disables the check
# (use when the admin is protected by VPN/SSO at the proxy instead).
ADMIN_ALLOWED_IPS = config("DJANGO_ADMIN_ALLOWED_IPS", default="", cast=Csv())

# --- Explicit cookie policy (secure flags are set in prod.py) ---
SESSION_COOKIE_HTTPONLY = True          # JS must never read the session
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 14 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
CSRF_COOKIE_HTTPONLY = True             # forms use {% csrf_token %}, no JS access needed
CSRF_COOKIE_SAMESITE = "Lax"
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True

ROOT_URLCONF = 'eve.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eve.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
SALEOR_GRAPHQL_URL = config("SALEOR_GRAPHQL_URL", default="")
SALEOR_CHANNEL = config("SALEOR_CHANNEL", default="default-channel")
SALEOR_API_TOKEN = config("SALEOR_API_TOKEN", default="")

# Shared secret for verifying Saleor webhook signatures (HMAC-SHA256)
SALEOR_WEBHOOK_SECRET = config("SALEOR_WEBHOOK_SECRET", default="")

# Checkout stays disabled until the Saleor integration tests pass against a
# real instance (see payments/tests.py::SaleorIntegrationTests). Flip only
# after that, and only with SALEOR_WEBHOOK_SECRET configured.
CHECKOUT_ENABLED = config("CHECKOUT_ENABLED", default=False, cast=bool)

# How long Mongo-cached Saleor products stay fresh before re-fetching
PRODUCT_CACHE_TTL_SECONDS = config("PRODUCT_CACHE_TTL_SECONDS", default=3600, cast=int)

# --- Cache / sessions: Redis when REDIS_URL is set, else per-process memory.
# Production requires REDIS_URL (prod.py) so rate limits, lockouts, and
# sessions are shared across workers.
REDIS_URL = config("REDIS_URL", default="")

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                # Passed through to redis.ConnectionPool
                "max_connections": config("REDIS_MAX_CONNECTIONS", default=50, cast=int),
                "socket_connect_timeout": 2,
                "socket_timeout": 2,
                "retry_on_timeout": True,
            },
            "TIMEOUT": 300,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

# cached_db: reads served from Redis, writes mirrored to PostgreSQL, so a
# Redis flush/eviction/failover never logs users out. PostgreSQL stays the
# authoritative store for sessions, orders, and payments.
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

# --- Email (password reset, email verification). Console backend by default;
# production configures SMTP in prod.py.
EMAIL_BACKEND = config(
    "EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@localhost")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME", default="eve_db"),
        "USER": config("DB_USER", default="eve_user"),
        "PASSWORD": config("DB_PASSWORD", default="password"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
        # Persistent connections with health checks; put PgBouncer in front
        # when worker count × CONN_MAX_AGE pressure approaches max_connections
        "CONN_MAX_AGE": config("DB_CONN_MAX_AGE", default=60, cast=int),
        "CONN_HEALTH_CHECKS": True,
    }
}
MONGODB = {
    "HOST": config("MONGODB_URI", default="mongodb://localhost:27017"),
    "DB_NAME": config("MONGODB_DB_NAME", default="EVEDB"),
    "MAX_POOL_SIZE": config("MONGODB_MAX_POOL_SIZE", default=50, cast=int),
}

# Reverse proxies whose X-Forwarded-For may be trusted for the client IP
# (rate limiting, admin allowlist). Empty = direct connections only.
TRUSTED_PROXIES = config("DJANGO_TRUSTED_PROXIES", default="", cast=Csv())

# --- Request size limits: bots and abuse, not legitimate form traffic
DATA_UPLOAD_MAX_MEMORY_SIZE = 1 * 1024 * 1024   # 1 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 1 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 200

REST_FRAMEWORK = {
    # Explicit: session auth only (no basic auth), authenticated by default,
    # JSON only — the browsable API is re-enabled in dev.py
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "30/min",
        "user": "120/min",
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        # 4xx/5xx responses and unhandled exceptions
        "django.request": {"level": "WARNING"},
        # CSRF failures, DisallowedHost, suspicious operations
        "django.security": {"level": "WARNING"},
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
