# Generated by Django 5.2.16 on 2026-07-29 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_webhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('cart_fingerprint', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('started', 'Started'), ('checkout_created', 'Checkout created'), ('completing', 'Completing'), ('completed', 'Completed'), ('failed', 'Failed safely'), ('unknown', 'Outcome unknown')], db_index=True, default='started', max_length=24)),
                ('saleor_checkout_id', models.CharField(blank=True, default='', max_length=100)),
                ('saleor_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('last_error', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'updated_at'], name='payments_ca_state_updated_idx')],
            },
        ),
    ]
